package main

import (
	"encoding/json"
	"flag"
	"io/ioutil"
	"log"
	"os"
	"os/signal"

	"github.com/arionsilver/twitch_stream_supporter/twitch"
)

// AuthInfo auth info
type AuthInfo struct {
	Discord            string `json:"discord"`
	Twitch             string `json:"twitch"`
	TwitchClientID     string `json:"twitch-client-id"`
	TwitchClientSecret string `json:"twitch-client-secret"`
}

func readAuthFile(filename string) (auth AuthInfo) {
	if filename == "" {
		log.Fatal("Authentication information filename must not be empty.")
	}

	file, err := ioutil.ReadFile(filename)
	if err != nil {
		log.Fatalf("An error occured while reading authentication file: %s", err)
	}

	if err = json.Unmarshal(file, &auth); err != nil {
		log.Fatalf("An error occured while parsing authentication file: %s", err)
	}

	return
}

func readConfigFile(filename string) (config twitch.Config) {
	if filename == "" {
		log.Fatal("Configuration filename must not be empty.")
	}

	file, err := ioutil.ReadFile(filename)
	if err != nil {
		log.Fatalf("An error occurred while reading the configuration file: %s", err)
	}

	if err = json.Unmarshal(file, &config); err != nil {
		log.Fatalf("An error occured while parsing configuration file: %s", err)
	}

	return
}

func main() {
	var authFile string
	var configFile string
	var twitchTokenFile string

	flag.StringVar(&authFile, "auth", "", "authentication information file for both twitch and discord")
	flag.StringVar(&configFile, "config", "", "configuration file")
	flag.StringVar(&twitchTokenFile, "token", "", "app token file for twitch authorization. File is automatically generated by program")
	flag.Parse()

	auth := readAuthFile(authFile)
	config := readConfigFile(configFile)

	twitchQuitSignal := make(chan bool)
	discordQuitSignal := make(chan bool)

	twitchExit := startTwitchHelper(auth, twitchTokenFile, config, twitchQuitSignal)
	discordExit := startDiscordBot(auth.Discord, config, discordQuitSignal)
	quitSignal := make(chan os.Signal)
	signal.Notify(quitSignal, os.Interrupt, os.Kill)

	select {
	case quit := <-twitchExit:
		if quit {
			log.Print("Twitch helper called exit")
			discordQuitSignal <- true
		}
	case quit := <-discordExit:
		if quit {
			log.Print("Discord helper called exit")
			twitchQuitSignal <- true
		}
	case <-quitSignal:
		twitchQuitSignal <- true
		discordQuitSignal <- true
		log.Print("Interrupt called")
	}
}
